name: ravenlink
services:
- environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
  name: ravenlink
  build_command: npm run build
  run_command: npm start
  output_dir: _static
